name: Run Tests

on:
  push:
    branches:
      - "develop"
  pull_request:
  workflow_dispatch:

env:
  RUST_CHANNEL: "stable"
  RUST_TEST_CHANNEL: "nightly"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: moonrepo/setup-rust@v0
        with:
          cache: false
          channel: ${{ env.RUST_TEST_CHANNEL }}
      - name: cargo install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --codecov --output-path codecov.json
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: codecov.json
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain and codspeed
        uses: moonrepo/setup-rust@v0
        with:
          channel: ${{ env.RUST_CHANNEL }}
          cache-target: bench
          bins: cargo-codspeed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the benchmark target(s)
        run: cargo codspeed build --profile bench
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain and clippy
        uses: moonrepo/setup-rust@v0
        with:
          channel: ${{ env.RUST_CHANNEL }}
          components: clippy
      - name: Run clippy
        run: cargo clippy --tests -- -D warnings
